---
title: "Resources (El Recursos)"
date: "(updated 4/28/2020)"
output: 
  html_document:
    toc: true
    toc_float: true
---

***

# *English* 

### NYC Updates: 

Text COVID (for Spanish COVIDESP) to 692692

### Internet/Electronics:

**Spectrum** is providing free internet service to students without internet access - please call 1-844-488-8398 for further information.

**Electronics** NYC DOE is able to provide electronic devices for public health students who need them for remote learning:  https://coronavirus.schools.nyc/RemoteLearningDevice
You can also call 718-935-5100, and choose option 5.

### Hospital Care: 
Hospitals have suspended all visitation **except** for patients in labor and delivery, pediatric patients, patients with disabilities, and patients in imminent end-of-life situations, who are permitted to have a **patient support person** with them.  https://bit.ly/hospitalvisitation

### Virtual Urgent Care:
**Virtual Urgent Care** from NewYork-Presbyterian lets you see a board-certified emergency or pediatric emergency physician* from Columbia or Weill Cornell Medicine right on your phone, tablet, or computer.

* Flexibility with services offered 7 days a week (8am-Midnight)

* https://www.nyp.org/ondemand/urgent-care 

### Mental Health:
The city has set up a confidential 24/7 mental health helpline:  you can connect with help by phone (1-888-NYC-WELL), by text (text "well" to 65173), or by chat @nyc.gov/nycwell

### Food:

* Families can visit their nearest **DOE school** to pick up grab-and-go breakfast starting at 7:30 AM and lunch starting at 11:30 AM. Families can find their nearest school by visiting https://www.nycenet.edu/schoolsearch or by calling 311.

* Beginning Monday 4/3, **ALL New Yorkers in more than 400 Meal Hubs** can pick up 3 free meals Monday - Friday:  https://schools.nyc.gov/freemeals

***

# *Español*

### Informe de Recursos en NYC:

Envíe un mensaje de texto COVID (para español COVIDESP) al 692692

### Internet gratis:

**Spectrum** ofrece servicio de internet gratuito a estudiantes sin acceso a internet; llame al 1-844-488-8398 para obtener más información.

Familias del Depto. del Educacion:  **obtengan su dispositivo del aprendizaje**:  https://coronavirus.schools.nyb/RemoteLearningDevices.
Para solicitar un dispositivo de aprendizaje remoto por telefono, ilame al 718-935-5100 y elija la opcion 5.

### Atención Hospitalaria:
Los hospitales han suspendido todas las visitas. Se acepta solo una persona de apoyo para pacientes en trabajo de parto y parto; pacientes pediátricos, pacientes con discapacidades o en situaciones donde está en riesgo la vida del paciente.

### Atención Medica Virtual (comuníquese vía el internet):

**Virtual Urgent Care** de New York-Presbyterian le permite ver a un médico certificado de emergencia, sea pediatra o para adultos de Columbia o Weill Cornell Medicine directamente, por su teléfono, tableta o computadora.

* Flexibilidad con los servicios ofrecidos los 7 días de la semana (8 de la mañana a medianoche)

* https://www.nyp.org/ondemand/urgent-care

### Salud Mental:
La ciudad ha establecido una línea de ayuda confidencial de salud mental 24/7: Llame al (1-888-NYC-WELL); exriba un mensaje con la palabra "well" to 65173, or inicie un chat @nyc.gov/nycwell . 

### Comida:

* Las familias pueden visitar su **escuela DOE** más cercana para recoger el desayuno para llevar a partir de las 7:30 a.m. y el almuerzo a partir de las 11:30 a.m. Las familias pueden encontrar su escuela más cercana visitando https://www.nycenet.edu/schoolsearch o llamando al 311.

* A partir del 4/3, 3 comidas gratis para **TODOS los neoyorquinos en mas de 400 centros**, de lunes a viernes.  Para más información visite la página: https://schools.nyc.gov/freemeals

***

# Helpful Websites
*CDC website:*

https://www.cdc.gov/coronavirus/2019-ncov/index.html

*About COVID-19*:

https://en.hesperian.org/hhg/Coronavirus



